# action.yml
name: 'z390 Java build'
description: 'Build z390 Jar files'
outputs:
  javaversion: # version of java
    description: 'The version of java used'
runs:
  using: 'docker'
  image: 'Dockerfile'
