name: Build z390 jar file
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Build z390 jar
        uses: ./.github/actions/buildjar 
      - name: Get current dir, build folder contents
        run: echo "$(pwd)";echo "$(ls -l build)"
